// qFoldIT Toolbelt for UNIGINE 2 — NodeCodeGenTools.cs
// Category: CodeGen
// Generates a NodeReference-based WorldLogic/component skeleton with a
// public field for every named world node requested, so AI-authored
// gameplay code has real, bindable references instead of magic strings.
// Mirrors UEFN Toolbelt's Verse @editable generation and qFoldIT Unity
// Toolbelt's codegen_monobehaviour.

using System.IO;
using System.Linq;
using System.Text;
using Newtonsoft.Json.Linq;
using Unigine;

namespace QFoldIT.Toolbelt
{
    public static class NodeCodeGenTools
    {
        public static void Register()
        {
            ToolRegistry.Register("codegen_node_component", "CodeGen",
                "Generates a WorldLogic-derived C# class with a public NodeReference field for each named world node, plus empty lifecycle methods.",
                CodegenNodeComponent);
        }

        private static object CodegenNodeComponent(JObject p)
        {
            string className = (string)p["class_name"];
            string objectNamesCsv = (string)p["node_names"];
            string outputPath = (string)p["output_path"];
            string ns = (string)p["namespace"] ?? "";

            var names = (objectNamesCsv ?? "").Split(',').Select(n => n.Trim()).Where(n => n.Length > 0).ToList();
            var missing = names.Where(n => UnigineCompat.FindNodeByName(n) == null).ToList();

            var sb = new StringBuilder();
            sb.AppendLine("// Generated by qFoldIT Toolbelt — codegen_node_component");
            sb.AppendLine("// Assign the referenced nodes from the World Nodes panel into the fields below,");
            sb.AppendLine("// or resolve them by name at runtime via World.GetNodeByName if you prefer late binding.");
            sb.AppendLine("using Unigine;");
            sb.AppendLine();

            bool hasNs = !string.IsNullOrEmpty(ns);
            if (hasNs) { sb.AppendLine($"namespace {ns}"); sb.AppendLine("{"); }

            sb.AppendLine($"    public class {className} : WorldLogic");
            sb.AppendLine("    {");
            foreach (var n in names)
            {
                var fieldName = char.ToLowerInvariant(n[0]) + Sanitize(n).Substring(1);
                sb.AppendLine($"        /// <summary>World node: {n}</summary>");
                sb.AppendLine($"        public Node {fieldName};");
            }
            sb.AppendLine();
            sb.AppendLine("        public override int Init()");
            sb.AppendLine("        {");
            foreach (var n in names)
            {
                var fieldName = char.ToLowerInvariant(n[0]) + Sanitize(n).Substring(1);
                sb.AppendLine($"            {fieldName} = World.GetNodeByName(\"{n}\");");
            }
            sb.AppendLine("            return 1;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override int Update() { return 1; }");
            sb.AppendLine("        public override int Shutdown() { return 1; }");
            sb.AppendLine("    }");
            if (hasNs) sb.AppendLine("}");

            string dataRoot = Engine.Get().GetSourceDataPath() ?? ".";
            var fullPath = Path.Combine(dataRoot, outputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath) ?? ".");
            File.WriteAllText(fullPath, sb.ToString());

            return new
            {
                success = true,
                class_name = className,
                path = outputPath,
                fields_generated = names.Count,
                nodes_not_found_in_world = missing
            };
        }

        private static string Sanitize(string raw)
        {
            var clean = new string(raw.Where(char.IsLetterOrDigit).ToArray());
            return string.IsNullOrEmpty(clean) ? "field" : clean;
        }
    }
}
