// qFoldIT Toolbelt for UNIGINE 2 — ProjectSetupTools.cs
// Category: Project

using System.IO;
using System.Linq;
using Newtonsoft.Json.Linq;
using Unigine;

namespace QFoldIT.Toolbelt
{
    public static class ProjectSetupTools
    {
        private static readonly string[] StandardFolders =
        {
            "logic", "logic/managers", "logic/gameplay", "logic/ui",
            "meshes", "materials", "textures", "sounds", "sounds/music", "sounds/sfx",
            "worlds", "nodes", "nodes/environment", "nodes/characters", "nodes/props",
            "animations", "editor_scripts"
        };

        public static void Register()
        {
            ToolRegistry.Register("project_setup", "Project",
                "Creates a standard folder structure under data/<ProjectName> and generates a boilerplate <ProjectName>GameManager WorldLogic C# class.",
                ProjectSetup);
        }

        private static object ProjectSetup(JObject p)
        {
            string rawName = (string)p["project_name"] ?? "MyGame";
            string safeName = new string(rawName.Where(char.IsLetterOrDigit).ToArray());
            if (string.IsNullOrEmpty(safeName)) safeName = "MyGame";

            string dataRoot = Engine.Get().GetSourceDataPath() ?? ".";
            string root = Path.Combine(dataRoot, safeName);

            int foldersCreated = 0;
            foreach (var folder in StandardFolders)
            {
                var full = Path.Combine(root, folder);
                if (!Directory.Exists(full)) { Directory.CreateDirectory(full); foldersCreated++; }
            }

            var scriptDir = Path.Combine(root, "logic", "managers");
            Directory.CreateDirectory(scriptDir);
            var scriptPath = Path.Combine(scriptDir, $"{safeName}GameManager.cs");
            File.WriteAllText(scriptPath, GenerateGameManagerSource(safeName));

            return new
            {
                success = true,
                project_name = safeName,
                folders_created = foldersCreated,
                script_generated = Path.Combine(safeName, "logic", "managers", $"{safeName}GameManager.cs")
            };
        }

        private static string GenerateGameManagerSource(string projectName) =>
$@"// Generated by qFoldIT Toolbelt — project_setup
// Register this as a WorldLogic component (World Nodes panel or
// EngineInit) to hook Init/Update/Shutdown.
using Unigine;

namespace {projectName}
{{
    /// <summary>
    /// Boilerplate world logic entry point. Wire round flow, scoring, and
    /// win conditions here — generated as a starting point, not a final
    /// implementation.
    /// </summary>
    public class {projectName}GameManager : WorldLogic
    {{
        public static {projectName}GameManager Instance {{ get; private set; }}

        public override int Init()
        {{
            Instance = this;
            Log.Message(""[{projectName}GameManager] Initialized.\n"");
            return 1;
        }}

        public override int Update()
        {{
            return 1;
        }}

        public override int Shutdown()
        {{
            return 1;
        }}
    }}
}}
";
    }
}
